image: gitpod/workspace-dotnet
vscode:
  extensions:
    - muhammad-sammy.csharp
    - ionide.ionide-fsharp
tasks:
  - command: dotnet tool restore && dotnet restore
ports:
  - port: 8080
    onOpen: open-browser